### ISSUE TITLE
cdn.jsdelivr.net 证书出现问题了

### ISSUE THREAD

**Issue by Francklin** [hostsoft/whmcs_payment_vmq#3]
cdn.jsdelivr.net 证书出现问题了。可以使用www.webcache.cn替代。

**Comment by ninetian** [comment]
可以使用 fastly.jsdelivr.net 替代， 
CN域名的大多不敢用吧  随时封的

**Comment by Francklin** [comment]
这个是国内备案过的，坚持长期运营的。
