### ISSUE TITLE
你好，可以把返回修改到支付的帐单吗？

### ISSUE THREAD

**Issue by cnen2018** [hostsoft/whmcs_payment_vmq#4]
现在直接返回到客户中心，想返回收当前帐单更新支付状态.

**Comment by ninetian** [comment]
自己修改下就好了

https://github.com/hostsoft/whmcs_payment_vmq/blob/master/vmq_whmcs_plugin/modules/gateways/wanyivmq.php

这个文件里的

```php
$returnUrl = WHMCS\Config\Setting::getValue("SystemURL").'/clientarea.php';
```

改为

```php 
$returnUrl = WHMCS\Config\Setting::getValue("SystemURL")."/viewinvoice.php?id={$params['invoiceid']}&paymentsuccess=true";

```
会返回支付时候的订单页了， 但是通知状态不是这个文件文件更新的 ，是异步回调的  callback那个才会更新

**Comment by cnen2018** [comment]
你好，可以了，谢谢.
我自己修改了下，在点支付的时候在同窗口更好一些，然后支付后返回原帐单，顺利完成了.
